# 7 - Escreva uma consulta SQL que exiba o nome dos clientes e a quantidade de telefones encontrados. 

CREATE TABLE CLIENTES (
    CPF CHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL
);

CREATE TABLE TELEFONES (
    CPF_CLIENTE CHAR(11),
    DDD CHAR(2) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    PRIMARY KEY (CPF_CLIENTE, TELEFONE),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF) ON DELETE CASCADE
);

SELECT CLIENTES.NOME, COUNT(TELEFONES.TELEFONE) AS QUANTIDADE_TELEFONES
FROM CLIENTES
JOIN TELEFONES ON CLIENTES.CPF = TELEFONES.CPF_CLIENTE
GROUP BY CLIENTES.NOME
HAVING COUNT(TELEFONES.TELEFONE) >= 1;


