# 8 – Escreva o comando SQL necessário para excluir todos os clientes que possuam o sobrenome ‘santos’.

CREATE TABLE CLIENTES (
    CPF CHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT NOT NULL
);

CREATE TABLE TELEFONES (
    CPF_CLIENTE CHAR(11),
    DDD CHAR(2) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    PRIMARY KEY (CPF_CLIENTE, TELEFONE),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF) ON DELETE CASCADE
);


DELETE FROM CLIENTES WHERE NOME LIKE '%Santos%';
